import type { Investigation, User, Reply } from "../types/investigation"

export const mockUser: User = {
  address: "0x1234...5678",
  username: "InvestigatorX",
  avatar: "/placeholder.svg?height=40&width=40",
  reputation: 850,
  totalEarned: 125.5,
  investigationsCreated: 12,
  verificationsCompleted: 89,
}

export const mockInvestigations: Investigation[] = [
  {
    id: "1",
    title: "Suspicious Trading Activity on DEX Platform",
    content:
      "Multiple large transactions occurring just before major announcements suggest possible insider trading. Pattern analysis shows consistent behavior over 3 months. I've identified wallet addresses that consistently make large trades 24-48 hours before major protocol announcements. The timing correlation is too strong to be coincidental.",
    author: "CryptoDetective",
    authorAddress: "0xabcd...efgh",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    verificationDeadline: new Date(Date.now() + 22 * 60 * 60 * 1000),
    status: "pending",
    votes: { correct: 45, false: 12, maybe: 23 },
    userVotes: {},
    tags: ["DeFi", "Trading", "Insider Trading"],
    evidence: ["Transaction hash: 0x123...", "Timing analysis chart", "Wallet connection graph"],
    rewardPool: 50,
  },
  {
    id: "2",
    title: "Fake Social Media Influence Campaign",
    content:
      "Coordinated bot network promoting specific cryptocurrency projects. Analysis reveals 500+ fake accounts with similar posting patterns. These accounts were created in batches and follow identical engagement patterns across multiple platforms.",
    author: "SocialSleuth",
    authorAddress: "0x9876...5432",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    verificationDeadline: new Date(Date.now() + 19 * 60 * 60 * 1000),
    status: "pending",
    votes: { correct: 67, false: 8, maybe: 15 },
    userVotes: {},
    tags: ["Social Media", "Bots", "Manipulation"],
    evidence: ["Bot account list", "Posting pattern analysis", "Network visualization"],
    rewardPool: 75,
  },
  {
    id: "3",
    title: "Smart Contract Vulnerability in Popular DApp",
    content:
      "Discovered potential reentrancy attack vector in lending protocol. Could result in significant fund drainage if exploited. The vulnerability exists in the withdraw function where external calls are made before state updates.",
    author: "SecurityAuditor",
    authorAddress: "0x5555...7777",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    verificationDeadline: new Date(Date.now() - 2 * 60 * 60 * 1000),
    status: "verified",
    votes: { correct: 89, false: 5, maybe: 6 },
    userVotes: {},
    tags: ["Smart Contract", "Security", "DeFi"],
    evidence: ["Contract code analysis", "Proof of concept", "Similar exploits"],
    rewardPool: 100,
  },
]

export const mockReplies: Reply[] = [
  {
    id: "reply-1",
    investigationId: "1",
    content:
      "I can confirm this pattern. I've been tracking similar wallet behavior and found 3 additional addresses that follow the same trading pattern. Here's the on-chain evidence showing the correlation between their trades and announcement timing.",
    author: "BlockchainAnalyst",
    authorAddress: "0xaaaa...bbbb",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    votes: { correct: 12, false: 2, maybe: 1 },
    userVotes: {},
    type: "evidence",
  },
  {
    id: "reply-2",
    investigationId: "1",
    content:
      "This is concerning. Have you considered that these could be protocol team members or advisors who have legitimate early access to information? We should verify if these addresses are connected to the team before concluding insider trading.",
    author: "DevilsAdvocate",
    authorAddress: "0xcccc...dddd",
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
    votes: { correct: 8, false: 15, maybe: 5 },
    userVotes: {},
    type: "analysis",
  },
  {
    id: "reply-3",
    investigationId: "1",
    content:
      "Great investigation! I've cross-referenced these addresses with known MEV bot operators and found no matches. This strengthens the insider trading hypothesis. Should we report this to the relevant authorities?",
    author: "ComplianceExpert",
    authorAddress: "0xeeee...ffff",
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    votes: { correct: 18, false: 1, maybe: 3 },
    userVotes: {},
    type: "analysis",
  },
  {
    id: "reply-4",
    investigationId: "2",
    content:
      "I've analyzed the bot network and can confirm the coordinated behavior. The accounts use similar profile pictures (generated by the same AI model) and post at synchronized intervals. Here's my detailed analysis of their posting patterns.",
    author: "BotHunter",
    authorAddress: "0x1111...2222",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    votes: { correct: 25, false: 0, maybe: 2 },
    userVotes: {},
    type: "evidence",
  },
  {
    id: "reply-5",
    investigationId: "3",
    content:
      "I've reviewed the smart contract code and can confirm the reentrancy vulnerability. The issue is in line 247 of the lending contract. I've also found that the same pattern exists in 2 other functions. This needs immediate attention.",
    author: "SmartContractAuditor",
    authorAddress: "0x3333...4444",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    votes: { correct: 45, false: 1, maybe: 0 },
    userVotes: {},
    type: "evidence",
  },
]
